apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: default
  labels:
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-container
        image: chukkap/kubernetesproject:10
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
